### ISSUE TITLE
error when building docker

### ISSUE THREAD

**Issue by ceilwoo** [googlecreativelab/aiexperiments-ai-duet#20]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ai-duet@1.0.0 No description
npm WARN ai-duet@1.0.0 No license field.
/node_modules/webpack-cli/bin/webpack.js:242
				throw err;
				^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/node_modules/webpack-cli/bin/convert-argv.js:7:24)
    at Module._compile (/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at yargs.parse (/node_modules/webpack-cli/bin/webpack.js:239:14)
    at Object.parse (/node_modules/yargs/yargs.js:543:18)
    at /node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
The command '/bin/sh -c npm install && webpack -p' returned a non-zero code: 1

**Comment by tetsuyasu** [comment]
Edit aiexperiments-ai-duet/Dockerfile to fix the problem.

<before>
RUN npm install webpack -g

<after>
RUN npm install webpack@1.12.14 -g

There is not much meaning in 1.12.14.
3.x or earlier is required.
